<script type="text/javascript">
   require([
       'jquery',
       'ConfigWise_ArWidget/js/form',
       'domReady!'
   ], function ($, form) {
       $(document).ready(function () {
           setTimeout(function () {    
               $(document).on('change', '[name="product[product_attribute_use]"]', function() {
                   form.showHideAttr();
               });
               form.showHideAttr();//This is added to trigger based on // the original value after just the page is loaded. since if it is //disabled by default it doesnt gets triggered
           },5000);
       });
   });
</script>
